extends: [setuptools_package,libflags]

dependencies:
  build: [nose]
  run: [nose]

sources:
 - key: tar.gz:322bmpxrd523kigyelmvaxa7iytwdnbq
   url: https://files.pythonhosted.org/packages/c4/e0/e05fee8b5425db6f83237128742e7e5ef26219b687ab8f0d41ed0422125e/pkgconfig-1.5.5.tar.gz
