extends: [autotools_package]

dependencies:
  # for the pkg-config wrapper
  run: [python]

defaults:
  # has a compiled-in default search path
  relocatable: false

sources:
- key: tar.gz:263p3njc3aobd5na4cqgfgu7ksaibhwj
  url: https://distfiles.dereferenced.org/pkgconf/pkgconf-1.8.0.tar.gz

build_stages:
- name: install_wrapper
  after: install
  files: [pkg-config-wrapper]
  handler: bash
  bash: |
    install -c -m 755 _hashdist/pkg-config-wrapper "${ARTIFACT}"/bin/pkg-config

when_build_dependency:
- prepend_path: PATH
  value: '${ARTIFACT}/bin'
- set: PKG_CONFIG_EXECUTABLE
  value: '${ARTIFACT}/bin/pkg-config'
